apiVersion: apps/v1
kind: Deployment
metadata:
  name: unreal-operations
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unreal-operations
  template:
    metadata:
      labels:
        app: unreal-operations
    spec:
      containers:
        - name: unreal-operations
          image: quay.io/mradecke/unreal-operations:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            